### ISSUE TITLE
Create representative website on GitHubPages

### ISSUE THREAD

**Issue by KSlosarczyk** [ProgramowanieSystemowMobilnych/ShopZoid#22]
As mentioned in project requirements: 

> G. Utworzenie witryny internetowej projektu
• Lokalizacja
o Wykorzystanie funkcjonalności Github Pages
o Adres witryny projektu powinien wyglądać następująco:
http(s)://<username>.github.io/<projectname>
o https://pages.github.com/
o https://help.github.com/en/articles/user-organization-and-project-pages
• Forma
o Atrakcyjna postać
• Zawartość
o Charakterystyka projektu (temat, opis projektu)
o Cel aplikacji, jej główne cechy, screeny prezentujące zasadnicze
funkcjonalności aplikacji
o Linki do składowych projektu

**Comment by KSlosarczyk** [comment]
Ok, I'll take this exercise.

**Comment by KSlosarczyk** [comment]
[Representative website](https://programowaniesystemowmobilnych.github.io/ShopZoid.io/)

Need just to add few texts.

**Comment by KSlosarczyk** [comment]
@Trzmiel1 
You can try to add descriptions to points on the representative site.

**Comment by Trzmiel1** [comment]
added descriptions to points  and useful links
