### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by mrdzanek** [ProgramowanieSystemowMobilnych/ShopZoid#5]
create basic layout of navigation bar - with nonactive links

**Comment by KSlosarczyk** [comment]
@mrdzanek 
Temat jest juz ponizej:
[NavBar](https://github.com/ProgramowanieSystemowMobilnych/ShopZoid/issues/1)

**Comment by mrdzanek** [comment]
> @mrdzanek
> Temat jest juz ponizej:
> [NavBar](https://github.com/ProgramowanieSystemowMobilnych/ShopZoid/issues/1)

closed due to duplicate
