### ISSUE TITLE
Test application in Lighthouse to find PWA issues

### ISSUE THREAD

**Issue by mrdzanek** [ProgramowanieSystemowMobilnych/ShopZoid#7]
test after step of serviceworker is finished

**Comment by Trzmiel1** [comment]
![FirstTestingInLighthouse](https://user-images.githubusercontent.com/48628363/82147945-84711d80-9851-11ea-8bc8-f135329587f9.png)
after first testing in Lighthouse web app gets 87/100 in Performance metrics

**Comment by Trzmiel1** [comment]
![FirstTestingInLighthouse](https://user-images.githubusercontent.com/48628363/82147900-4116af00-9851-11ea-8d62-ca482f2bd063.png)

**Comment by Trzmiel1** [comment]
![1](https://user-images.githubusercontent.com/48628363/82158063-a71d2980-9885-11ea-9d50-5687bb4748e3.jpg)
Version deployed on Wizard Server

**Comment by Trzmiel1** [comment]
![1](https://user-images.githubusercontent.com/48628363/82158094-f95e4a80-9885-11ea-8008-d0df26db88b8.jpg)
